<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="xunit.v3" />
    <ProjectReference Include="..\..\src\ConnectionClue.Analysis\ConnectionClue.Analysis.csproj" />
  </ItemGroup>
</Project>
