using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using ConnectionClue.Presentation.Diagnostics;

namespace ConnectionClue.Presentation.Tests;

public sealed partial class ResultsMhtmlTests
{
    private static readonly byte[] Png = Convert.FromBase64String(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/tYQAAAAASUVORK5CYII=");

    private static ResultsExportData Report(string text = "Delay: 25 ms") => new(
        "en-US", false, "Check results", "Quick check", "results",
        [new("Measurements", [text])], "Check visuals", ["Overview", "Delay chart"],
        [new("Measurements over time", ["Time", "Result"], [new[] { "1 s", text }], "Some samples were omitted.")],
        "This check only.");

    [Fact]
    public void Archive_embeds_html_and_every_png_with_matching_content_ids()
    {
        string archive = ResultsMhtml.Build(Report(), [new("Overview", Png), new("Delay chart", Png)]);
        var parts = Parts(archive);
        Assert.Equal(3, parts.Count);
        Assert.Contains("start=\"<report@connectionclue>\"", archive, StringComparison.Ordinal);
        Assert.Contains("Content-Type: text/html; charset=utf-8", parts[0].Headers, StringComparison.Ordinal);
        Assert.Contains("Content-ID: <report@connectionclue>", parts[0].Headers, StringComparison.Ordinal);
        string html = Encoding.UTF8.GetString(parts[0].Bytes);
        for (int i = 0; i < 2; i++)
        {
            Assert.Contains($"src=\"cid:visual-{i}@connectionclue\"", html, StringComparison.Ordinal);
            Assert.Contains($"Content-ID: <visual-{i}@connectionclue>", parts[i + 1].Headers, StringComparison.Ordinal);
            Assert.Contains("Content-Type: image/png", parts[i + 1].Headers, StringComparison.Ordinal);
            Assert.Equal(Png, parts[i + 1].Bytes);
        }
        Assert.Contains("alt=\"Overview\"", html, StringComparison.Ordinal);
        Assert.Contains("<figcaption>Delay chart</figcaption>", html, StringComparison.Ordinal);
        Assert.Contains("<th scope=\"col\">Result</th>", html, StringComparison.Ordinal);
        Assert.Contains("<td>Delay: 25 ms</td>", html, StringComparison.Ordinal);
        Assert.Contains("Some samples were omitted.", html, StringComparison.Ordinal);
        Assert.Contains("This check only.", html, StringComparison.Ordinal);
        Assert.DoesNotContain("src=\"https:", html, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("<link ", html, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("fetch(", html, StringComparison.Ordinal);
    }

    [Fact]
    public void Archive_uses_ascii_headers_crlf_and_76_character_base64_lines()
    {
        string archive = ResultsMhtml.Build(Report(new string('x', 800)), [new("Chart", Png)]);
        Assert.DoesNotContain(archive, c => c > 127);
        Assert.DoesNotContain("\n", archive.Replace("\r\n", "", StringComparison.Ordinal), StringComparison.Ordinal);
        foreach (var part in Parts(archive))
        {
            Assert.Contains("Content-Transfer-Encoding: base64", part.Headers, StringComparison.Ordinal);
            Assert.All(part.Encoded.Split("\r\n", StringSplitOptions.RemoveEmptyEntries), line => Assert.InRange(line.Length, 1, 76));
        }
    }

    [Fact]
    public void Non_English_content_and_right_to_left_direction_survive_without_running_script()
    {
        const string text = "Türkçe — فحص الاتصال — 接続テスト";
        var data = Report(text) with { Language = "ar", RightToLeft = true, Title = text };
        string html = Encoding.UTF8.GetString(Parts(ResultsMhtml.Build(data, []))[0].Bytes);
        Assert.Contains("<html lang=\"ar\" dir=\"rtl\" data-theme=\"dark\">", html, StringComparison.Ordinal);
        Assert.Contains(text, WebUtility.HtmlDecode(html), StringComparison.Ordinal);
        Assert.Contains("--cp-bg:", html, StringComparison.Ordinal);
        Assert.Contains("background: var(--cp-bg)", html, StringComparison.Ordinal);
        Assert.Contains("<li>", html, StringComparison.Ordinal); // Content is static, not generated by JavaScript.
        Assert.DoesNotContain("<figure>", html, StringComparison.Ordinal);
    }

    [Fact]
    public void Export_uses_readable_regular_text_and_generous_spacing()
    {
        string html = Encoding.UTF8.GetString(Parts(ResultsMhtml.Build(Report(), []))[0].Bytes);
        Assert.Contains("font-family: \"Segoe UI\", Aptos, Calibri", html, StringComparison.Ordinal);
        Assert.Contains("font-size: 1.125rem; font-weight: 400; font-style: normal; font-stretch: normal;", html, StringComparison.Ordinal);
        Assert.Contains("line-height: 1.75; letter-spacing: normal;", html, StringComparison.Ordinal);
        Assert.Contains("max-inline-size: 72ch", html, StringComparison.Ordinal);
        Assert.Contains("li { margin-block: 0.5rem; }", html, StringComparison.Ordinal);
        Assert.Contains("font: inherit; font-variant-numeric: tabular-nums;", html, StringComparison.Ordinal);
        Assert.Contains("padding: 0.75rem 1rem;", html, StringComparison.Ordinal);
        Assert.DoesNotContain("@font-face", html, StringComparison.Ordinal);
    }

    [Fact]
    public void Every_data_field_is_html_encoded_and_cannot_inject_markup_or_mime_headers()
    {
        const string text = "\"><img src=\"https://evil.invalid/x\" onerror=\"alert(1)\"><script>attack()</script>&\r\nContent-Type: evil";
        var data = Report(text) with
        {
            Language = text,
            Title = text,
            Subtitle = text,
            Sections = [new(text, [text])],
            VisualsHeading = text,
            Tables = [new(text, [text], [new[] { text }], text)],
            Footer = text,
        };
        var parts = Parts(ResultsMhtml.Build(data, [new(text, Png)]));
        string html = Encoding.UTF8.GetString(parts[0].Bytes);
        Assert.Contains(WebUtility.HtmlEncode(text), html, StringComparison.Ordinal);
        Assert.DoesNotContain(text, html, StringComparison.Ordinal);
        Assert.DoesNotContain("<script>attack()", html, StringComparison.Ordinal);
        Assert.DoesNotContain("<img src=\"https://evil", html, StringComparison.Ordinal);
        Assert.All(parts, part => Assert.DoesNotContain("evil", part.Headers, StringComparison.Ordinal));
    }

    private sealed record Part(string Headers, string Encoded, byte[] Bytes);

    private static List<Part> Parts(string archive)
    {
        string boundary = Boundary().Match(archive).Groups[1].Value;
        Assert.NotEmpty(boundary);
        Assert.EndsWith("--" + boundary + "--\r\n", archive, StringComparison.Ordinal);
        var parts = new List<Part>();
        foreach (string part in archive.Split("--" + boundary, StringSplitOptions.None).Skip(1).SkipLast(1))
        {
            int body = part.IndexOf("\r\n\r\n", StringComparison.Ordinal);
            Assert.True(body >= 0);
            string encoded = part[(body + 4)..];
            parts.Add(new(part[..body], encoded, Convert.FromBase64String(encoded)));
        }
        return parts;
    }

    [GeneratedRegex("boundary=\"([^\"]+)\"")]
    private static partial Regex Boundary();
}
